package com.cloudlibrary.dao;

import java.util.List;

import com.cloudlibrary.domain.Book;
import com.github.pagehelper.Page;

public interface BookMapper {
	//分页1.返回数据类型,使用Page<E>
	Page<Book> searchBook(Book book);	
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated
     */
    //新增一条图书记录
    Integer insert(Book record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated
     */
   /** int insertSelective(Book record);
	 *
     * @mbg.generated
     * 根据id查询一条book记录
     */
    Book selectByPrimaryKey(Integer bookId);

    /**
     *更新图书信息
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Book record);

    
    
}