package com.javan.entity;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_id
     *
     * @mbg.generated
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_name
     *
     * @mbg.generated
     */
    private String categoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.category_num
     *
     * @mbg.generated
     */
    private Integer categoryNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.is_null
     *
     * @mbg.generated
     */
    private String isNull;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_id
     *
     * @return the value of category.category_id
     *
     * @mbg.generated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_id
     *
     * @param categoryId the value for category.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_name
     *
     * @return the value of category.category_name
     *
     * @mbg.generated
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_name
     *
     * @param categoryName the value for category.category_name
     *
     * @mbg.generated
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.category_num
     *
     * @return the value of category.category_num
     *
     * @mbg.generated
     */
    public Integer getCategoryNum() {
        return categoryNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.category_num
     *
     * @param categoryNum the value for category.category_num
     *
     * @mbg.generated
     */
    public void setCategoryNum(Integer categoryNum) {
        this.categoryNum = categoryNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.is_null
     *
     * @return the value of category.is_null
     *
     * @mbg.generated
     */
    public String getIsNull() {
        return isNull;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.is_null
     *
     * @param isNull the value for category.is_null
     *
     * @mbg.generated
     */
    public void setIsNull(String isNull) {
        this.isNull = isNull == null ? null : isNull.trim();
    }
}