package com.javan.entity;

public class Brand {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.brand_id
     *
     * @mbg.generated
     */
    private Integer brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.brand_name
     *
     * @mbg.generated
     */
    private String brandName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.brand_address
     *
     * @mbg.generated
     */
    private String brandAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.brand_phone
     *
     * @mbg.generated
     */
    private String brandPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.brand_id
     *
     * @return the value of brand.brand_id
     *
     * @mbg.generated
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.brand_id
     *
     * @param brandId the value for brand.brand_id
     *
     * @mbg.generated
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.brand_name
     *
     * @return the value of brand.brand_name
     *
     * @mbg.generated
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.brand_name
     *
     * @param brandName the value for brand.brand_name
     *
     * @mbg.generated
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.brand_address
     *
     * @return the value of brand.brand_address
     *
     * @mbg.generated
     */
    public String getBrandAddress() {
        return brandAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.brand_address
     *
     * @param brandAddress the value for brand.brand_address
     *
     * @mbg.generated
     */
    public void setBrandAddress(String brandAddress) {
        this.brandAddress = brandAddress == null ? null : brandAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.brand_phone
     *
     * @return the value of brand.brand_phone
     *
     * @mbg.generated
     */
    public String getBrandPhone() {
        return brandPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.brand_phone
     *
     * @param brandPhone the value for brand.brand_phone
     *
     * @mbg.generated
     */
    public void setBrandPhone(String brandPhone) {
        this.brandPhone = brandPhone == null ? null : brandPhone.trim();
    }
}