package com.cloudlibrary.domain;

public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_id
     *
     * @mbg.generated
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_name
     *
     * @mbg.generated
     */
    private String bookName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_isbn
     *
     * @mbg.generated
     */
    private String bookIsbn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_press
     *
     * @mbg.generated
     */
    private String bookPress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_author
     *
     * @mbg.generated
     */
    private String bookAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_pagination
     *
     * @mbg.generated
     */
    private Integer bookPagination;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_price
     *
     * @mbg.generated
     */
    private Double bookPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_uploadtime
     *
     * @mbg.generated
     */
    private String bookUploadtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_status
     *
     * @mbg.generated
     */
    private String bookStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_borrower
     *
     * @mbg.generated
     */
    private String bookBorrower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_borrowtime
     *
     * @mbg.generated
     */
    private String bookBorrowtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_returntime
     *
     * @mbg.generated
     */
    private String bookReturntime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_id
     *
     * @return the value of book.book_id
     *
     * @mbg.generated
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_id
     *
     * @param bookId the value for book.book_id
     *
     * @mbg.generated
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_name
     *
     * @return the value of book.book_name
     *
     * @mbg.generated
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_name
     *
     * @param bookName the value for book.book_name
     *
     * @mbg.generated
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_isbn
     *
     * @return the value of book.book_isbn
     *
     * @mbg.generated
     */
    public String getBookIsbn() {
        return bookIsbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_isbn
     *
     * @param bookIsbn the value for book.book_isbn
     *
     * @mbg.generated
     */
    public void setBookIsbn(String bookIsbn) {
        this.bookIsbn = bookIsbn == null ? null : bookIsbn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_press
     *
     * @return the value of book.book_press
     *
     * @mbg.generated
     */
    public String getBookPress() {
        return bookPress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_press
     *
     * @param bookPress the value for book.book_press
     *
     * @mbg.generated
     */
    public void setBookPress(String bookPress) {
        this.bookPress = bookPress == null ? null : bookPress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_author
     *
     * @return the value of book.book_author
     *
     * @mbg.generated
     */
    public String getBookAuthor() {
        return bookAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_author
     *
     * @param bookAuthor the value for book.book_author
     *
     * @mbg.generated
     */
    public void setBookAuthor(String bookAuthor) {
        this.bookAuthor = bookAuthor == null ? null : bookAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_pagination
     *
     * @return the value of book.book_pagination
     *
     * @mbg.generated
     */
    public Integer getBookPagination() {
        return bookPagination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_pagination
     *
     * @param bookPagination the value for book.book_pagination
     *
     * @mbg.generated
     */
    public void setBookPagination(Integer bookPagination) {
        this.bookPagination = bookPagination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_price
     *
     * @return the value of book.book_price
     *
     * @mbg.generated
     */
    public Double getBookPrice() {
        return bookPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_price
     *
     * @param bookPrice the value for book.book_price
     *
     * @mbg.generated
     */
    public void setBookPrice(Double bookPrice) {
        this.bookPrice = bookPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_uploadtime
     *
     * @return the value of book.book_uploadtime
     *
     * @mbg.generated
     */
    public String getBookUploadtime() {
        return bookUploadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_uploadtime
     *
     * @param bookUploadtime the value for book.book_uploadtime
     *
     * @mbg.generated
     */
    public void setBookUploadtime(String bookUploadtime) {
        this.bookUploadtime = bookUploadtime == null ? null : bookUploadtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_status
     *
     * @return the value of book.book_status
     *
     * @mbg.generated
     */
    public String getBookStatus() {
        return bookStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_status
     *
     * @param bookStatus the value for book.book_status
     *
     * @mbg.generated
     */
    public void setBookStatus(String bookStatus) {
        this.bookStatus = bookStatus == null ? null : bookStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_borrower
     *
     * @return the value of book.book_borrower
     *
     * @mbg.generated
     */
    public String getBookBorrower() {
        return bookBorrower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_borrower
     *
     * @param bookBorrower the value for book.book_borrower
     *
     * @mbg.generated
     */
    public void setBookBorrower(String bookBorrower) {
        this.bookBorrower = bookBorrower == null ? null : bookBorrower.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_borrowtime
     *
     * @return the value of book.book_borrowtime
     *
     * @mbg.generated
     */
    public String getBookBorrowtime() {
        return bookBorrowtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_borrowtime
     *
     * @param bookBorrowtime the value for book.book_borrowtime
     *
     * @mbg.generated
     */
    public void setBookBorrowtime(String bookBorrowtime) {
        this.bookBorrowtime = bookBorrowtime == null ? null : bookBorrowtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_returntime
     *
     * @return the value of book.book_returntime
     *
     * @mbg.generated
     */
    public String getBookReturntime() {
        return bookReturntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_returntime
     *
     * @param bookReturntime the value for book.book_returntime
     *
     * @mbg.generated
     */
    public void setBookReturntime(String bookReturntime) {
        this.bookReturntime = bookReturntime == null ? null : bookReturntime.trim();
    }

	@Override
	public String toString() {
		return "Book [bookId=" + bookId + ", bookName=" + bookName + ", bookIsbn=" + bookIsbn + ", bookPress="
				+ bookPress + ", bookAuthor=" + bookAuthor + ", bookPagination=" + bookPagination + ", bookPrice="
				+ bookPrice + ", bookUploadtime=" + bookUploadtime + ", bookStatus=" + bookStatus + ", bookBorrower="
				+ bookBorrower + ", bookBorrowtime=" + bookBorrowtime + ", bookReturntime=" + bookReturntime + "]";
	}
    
    
}