package com.cloudlibrary.domain;

public class Record {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_id
     *
     * @mbg.generated
     */
    private Integer recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_bookname
     *
     * @mbg.generated
     */
    private String recordBookname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_bookisbn
     *
     * @mbg.generated
     */
    private String recordBookisbn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_borrower
     *
     * @mbg.generated
     */
    private String recordBorrower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_borrowtime
     *
     * @mbg.generated
     */
    private String recordBorrowtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.record_remandtime
     *
     * @mbg.generated
     */
    private String recordRemandtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_id
     *
     * @return the value of record.record_id
     *
     * @mbg.generated
     */
    public Integer getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_id
     *
     * @param recordId the value for record.record_id
     *
     * @mbg.generated
     */
    public void setRecordId(Integer recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_bookname
     *
     * @return the value of record.record_bookname
     *
     * @mbg.generated
     */
    public String getRecordBookname() {
        return recordBookname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_bookname
     *
     * @param recordBookname the value for record.record_bookname
     *
     * @mbg.generated
     */
    public void setRecordBookname(String recordBookname) {
        this.recordBookname = recordBookname == null ? null : recordBookname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_bookisbn
     *
     * @return the value of record.record_bookisbn
     *
     * @mbg.generated
     */
    public String getRecordBookisbn() {
        return recordBookisbn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_bookisbn
     *
     * @param recordBookisbn the value for record.record_bookisbn
     *
     * @mbg.generated
     */
    public void setRecordBookisbn(String recordBookisbn) {
        this.recordBookisbn = recordBookisbn == null ? null : recordBookisbn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_borrower
     *
     * @return the value of record.record_borrower
     *
     * @mbg.generated
     */
    public String getRecordBorrower() {
        return recordBorrower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_borrower
     *
     * @param recordBorrower the value for record.record_borrower
     *
     * @mbg.generated
     */
    public void setRecordBorrower(String recordBorrower) {
        this.recordBorrower = recordBorrower == null ? null : recordBorrower.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_borrowtime
     *
     * @return the value of record.record_borrowtime
     *
     * @mbg.generated
     */
    public String getRecordBorrowtime() {
        return recordBorrowtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_borrowtime
     *
     * @param recordBorrowtime the value for record.record_borrowtime
     *
     * @mbg.generated
     */
    public void setRecordBorrowtime(String recordBorrowtime) {
        this.recordBorrowtime = recordBorrowtime == null ? null : recordBorrowtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.record_remandtime
     *
     * @return the value of record.record_remandtime
     *
     * @mbg.generated
     */
    public String getRecordRemandtime() {
        return recordRemandtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.record_remandtime
     *
     * @param recordRemandtime the value for record.record_remandtime
     *
     * @mbg.generated
     */
    public void setRecordRemandtime(String recordRemandtime) {
        this.recordRemandtime = recordRemandtime == null ? null : recordRemandtime.trim();
    }

	@Override
	public String toString() {
		return "Record [recordId=" + recordId + ", recordBookname=" + recordBookname + ", recordBookisbn="
				+ recordBookisbn + ", recordBorrower=" + recordBorrower + ", recordBorrowtime=" + recordBorrowtime
				+ ", recordRemandtime=" + recordRemandtime + "]";
	}
    
}